# Generated by Django 5.2.4 on 2025-08-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('FOTOGRAFIA', 'Fotografia')], default='', max_length=100),
        ),
    ]
